### ISSUE TITLE
Boost bottle for macOS 11?

### ISSUE THREAD

**Issue by jonkeane** [autobrew/homebrew-core#89]
We noticed recently that when our GitHub runners made the upgrade from 10.15 to 11.6, we stopped being able to install Boost.

Last 10.15 build: https://github.com/ursa-labs/arrow-r-nightly/runs/4425100054?check_suite_focus=true#step:6:137
First 11.6 build: https://github.com/ursa-labs/arrow-r-nightly/runs/4438311803?check_suite_focus=true#step:6:189

Ultimately, what I think is happening is that 10.15 is compatible (enough?) with one of the bottles in the formula, so it installs that. But 11.6 isn't, so it attempts to build from source (by downloading it from https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2). Except that the source isn't available anymore since bintray shutdown. 

It might be "as simple as" using the new artifactory URL for boost instead: https://boostorg.jfrog.io/artifactory/main/release/1.67.0/source/boost_1_67_0.tar.bz2

**Comment by jeroen** [comment]
Hmm this repo contains the legacy builds, it's only meant to run on macos 10.11 and 10.13. Would it be possible to run your workflow that uses this particular script in `macos: 10.15` for the time being (GHA will keep supporting that OS)

I don't think your suggestion to fix the src url will help much; we really want to test using the bottled dependencies, which are the ones we will eventually use for the CRAN package.

I'll also try to figure out why it thinks the bottle high-sierra incompatible with 11.x because it shouldn't. I suspect it has to do with the version of ruby on macos 11.x

**Comment by jeroen** [comment]
I think it will be difficult to get this legacy version of homebrew to work on macos 11 and up due to the [required changes in the macos versioning](https://github.com/Homebrew/brew/commit/8598b1186a32c98e7ed292880ef135182825c42e) and also the different major version of Ruby.

However the underlying problem here may be that we need to update the [script in apache arrow](https://github.com/apache/arrow/blob/HEAD/r/tools/autobrew) that uses this repo to build a version of apache-arrow. The current repo is mostly intended to build libarrow for macos 10.11 and 10.13. For newer versions of macos we use this tap to build arrow: https://github.com/autobrew/homebrew-cran

Also, the CRAN package now uses a much simpler script to [fetch a suitable binary of libarrow](https://github.com/autobrew/scripts/blob/master/apache-arrow), it no longer has to bootstrap a homebrew installation like we did early on.

**Comment by jonkeane** [comment]
Thanks for the details, we've [been meaning to update](https://issues.apache.org/jira/browse/ARROW-12590), and it sounds like this forces our hand. We will try that and let you know if we run into any issues
